version: '3'
services:
  api:
    build: ./springboot-api-docker
    ports:
      - "9090:9090"
  database:
   container_name: 'database'
   image: mysql
   environment:
     MYSQL_ROOT_PASSWORD: Warszawa5584
     MYSQL_PASSWORD: jacek
     MYSQL_DATABASE: animalsdb
     MYSQL_USER: jacek
   ports:
   - "3307:3306"