version: '3.1'
services:
  #service 1: definition of mysql
  db:
    image: mysql
    container_name: mysql-db6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: animal
    ports:
      - "3307:3306"
    volumes:
      - C:/tmp/06-Data/MySQLData/mysql-db6:/var/lib/mysql

#service 2: definition of phpMyAdmin
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:latest
#    container_name: my-php-myadmin
#    ports:
#      - "8081:80"
#    restart: always
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root

#service 3: definition of Springboot aplication
  api:
    image: api
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10101:10101"
    restart: always
    depends_on:
      - db