version: '3'
services:
  springboot-app:
    # container_name: spring-app
    image: springboot-app
    restart: always
    build: .
    ports:
      - 9000:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - C:/tmp/01-Data/mysqldb:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
























