version: '3.1'
services:
  #service 1: definition of mysql
  db:
    image: mysql
    container_name: mysql-db2
    restart: always
    environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: easyeat
    ports:
      - "3307:3306"
    volumes:
      - C:/tmp/02-Data/MySQLData/mysql-db2:/var/lib/mysql

#service 2: definition of phpMyAdmin
  phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: my-php-myadmin
        ports:
              - "8082:80"
        restart: always

        depends_on:
              - db
        environment:
              SPRING_DATASOURCE_USERNAME: root
              SPRING_DATASOURCE_PASSWORD: root