version: '3.1'
services:
#service 1: definition of mysql
  my-sql:
    image: mysql
    container_name: mysql-db4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    volumes:
      - C:/tmp/04-Data/MySQLData/mysql-db4:/var/lib/mysql

#service 2: definition of phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-php-myadmin
    ports:
      - "8081:80"
    restart: always
    depends_on:
      - my-sql
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  backendservice:
    image: backend-service
    container_name: backend-service-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    restart: always
    depends_on:
      - my-sql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db4:3306/mydb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root