version: '3.1'
services:
#service 1: definition of mysql
  db:
    image: mysql
    container_name: mysql-db3
    restart: always
    environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    volumes:
      - C:/tmp/03-Data/MySQLData/mysql-db3:/var/lib/mysql

#service 2: definition of phpMyAdmin
  phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: my-php-myadmin
        ports:
              - "8082:80"
        restart: always
        depends_on:
              - db
        environment:
              SPRING_DATASOURCE_USERNAME: root
              SPRING_DATASOURCE_PASSWORD: root

#service 3: Spring-Boot application
  dbservice:
    image: dbservice
    container_name: dbservice-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db3:3306/mydb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root